server:
  port : 8080
  error:
    include-message: always
    include-bindind-errors: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/financial_crypto
    username: financial_admin
    password: appadmin%
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
cripto-app:
  jwt:
    expiration: 86400000
    secret: w&$#Qa-qS4Tp+!hL9s-"h&dhU01oX9*<.GY2QKwf^Twdl>cb"Ebm#U0DVMN0"WF